issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/terraform-provider-apko:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/terraform-provider-apko/.github/workflows/digestabot.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
