name: Tests
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

permissions: {}

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: block
        allowed-endpoints: >
          *.blob.core.windows.net:443
          *.githubapp.com:443
          api.github.com:443
          checkpoint-api.hashicorp.com:443
          dl.google.com:443
          github.com:443
          go.dev:443
          objects.githubusercontent.com:443
          packages.wolfi.dev:443
          proxy.golang.org:443
          release-assets.githubusercontent.com:443
          releases.hashicorp.com:443
          storage.googleapis.com:443
          sum.golang.org:443

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: './.go-version'
        check-latest: true
        cache: false

    - uses: chainguard-dev/actions/setup-terraform@7bd1e94b2a1b7faa891392757de7d89489070c5c # v1.6.32
      with:
        terraform-version-file: '${{ github.workspace }}/.terraform-version'
        terraform-wrapper: false

    - run: go generate ./...

    - name: git diff
      run: |
        git diff --compact-summary --exit-code || \
          (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform:
        - '1.14.*'
        - '1.15.*'

    permissions:
      contents: read

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: block
        allowed-endpoints: >
          *.blob.core.windows.net:443
          *.githubapp.com:443
          api.github.com:443
          checkpoint-api.hashicorp.com:443
          dl.google.com:443
          github.com:443
          go.dev:443
          objects.githubusercontent.com:443
          packages.wolfi.dev:443
          proxy.golang.org:443
          release-assets.githubusercontent.com:443
          releases.hashicorp.com:443
          storage.googleapis.com:443
          sum.golang.org:443

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: './.go-version'
        check-latest: true
        cache: false

    - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      with:
        terraform_version: ${{ matrix.terraform }}
        terraform_wrapper: false

    - run: go mod download
    - run: go build -v .
    # TODO(jason): Enable -race
    - run: TF_ACC=1 go test -v -cover ./internal/provider/
