name: Tests
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

permissions: {}

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: './.go-version'
        check-latest: true
        cache: false

    - uses: chainguard-dev/actions/setup-terraform@7440e20e3e0bb180a2f6e330bcd53504e2ac8980 # v1.6.8
      with:
        terraform-version-file: '${{ github.workspace }}/.terraform-version'
        terraform-wrapper: false

    - run: go generate ./...

    - name: git diff
      run: |
        git diff --compact-summary --exit-code || \
          (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform:
        - '1.11.*'
        - '1.12.*'
        - '1.13.*'
        - '1.14.*'

    permissions:
      contents: read

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: './.go-version'
        check-latest: true
        cache: false

    - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      with:
        terraform_version: ${{ matrix.terraform }}
        terraform_wrapper: false

    - run: go mod download
    - run: go build -v .
    # TODO(jason): Enable -race
    - run: TF_ACC=1 go test -v -cover ./internal/provider/
